import { test, expect } from "@playwright/test";
import { BasePage } from "../pages/BasePage.js";

// Auto-generated by explorer/enrich.js from explorer/raw-login-flow.spec.js
// Regenerate instead of hand-editing whenever the recorded flow changes.

test.describe("Login and create order", () => {
  test("existing user can log in and create a new order", async ({ page }) => {
    const app = new BasePage(page);

    await page.goto("https://your-mendix-app-url/");
    await app.waitForMendixIdle();

    await app.mx("textBoxUsername").fill(process.env.MENDIX_TEST_USERNAME ?? "");
    await app.mx("textBoxPassword").fill(process.env.MENDIX_TEST_PASSWORD ?? "");
    await app.mx("buttonSignIn").click();
    await app.waitForMendixIdle();
    await app.expectNoErrorMessage();

    // Assertion inferred from the recording: after login the home page grid should load
    await expect(app.mx("gridMyOrders")).toBeVisible();

    await app.mx("buttonNewOrder").click();
    await app.waitForMendixIdle();

    await app.mx("dropDownCustomer").selectOption({ label: "Acme Corp" });
    await app.mx("textBoxQuantity").fill("3");
    await app.mx("buttonSaveOrder").click();
    await app.waitForMendixIdle();
    await app.expectNoErrorMessage();

    // Assertion inferred from the recording: saving returns to the grid with the new row present
    await expect(app.mx("gridMyOrders")).toContainText("Acme Corp");
  });
});
